=== huyvawn/learn-java/XML-Buoi1/src/Demo2/Student.dtd
<!ELEMENT Student (t2404+)>
<!ELEMENT t2404 (id,name,age,country)>
<!ELEMENT id (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT age (#PCDATA) >
<!ELEMENT country (#PCDATA) >

=== huyvawn/learn-java/XML-Buoi1/src/Demo2/Student.xml
<?xml version = "1.0" encoding ="UTF-8" ?>
<!DOCTYPE Student SYSTEM "Student.dtd">
<Student>
<t2404>
	<id>1</id>
	<name>Minh</name>
	<age>20</age>
	<country>HN</country>
</t2404>
<t2404>
	<id>2</id>
	<name>Minh2</name>
	<age>21</age>
	<country>SG</country>
</t2404>
</Student>
