=== huyvawn/learn-java/XML-Buoi1/src/bai1/Library.dtd
<!ELEMENT Library (Book+)>
<!ELEMENT Book (Title,Author,Year)>
<!ELEMENT Title (#PCDATA) >
<!ELEMENT Author (#PCDATA) >
<!ELEMENT Year (#PCDATA) >
<!ATTLIST Book Type CDATA #REQUIRED >

=== huyvawn/learn-java/XML-Buoi1/src/bai1/Library.xml
<?xml version="1.0" encoding ="UTF-8" ?>
<!DOCTYPE Library SYSTEM "Library.dtd" >
<Library>
<Book Type="Comic">
<Title>Doraemon</Title>
<Author>abc</Author>
<Year>2000</Year>
</Book>
<Book Type="Anime">
<Title>Conan</Title>
<Author>xyz</Author>
<Year>2001</Year>
</Book>
</Library>
